@url = https://8080-danisborges-apiquestao0-7finnr5p3m8.ws-us118.gitpod.io

GET {{url}}/categorias

###
GET {{url}}/categorias/3

###
POST {{url}}/categorias
Content-Type: application/json

{
    "nome" : "Biologia"
}

###
PUT {{url}}/categorias/3
Content-Type: application/json

{
    "nome" : "História"
}

###
DELETE {{url}}/categorias/1