@url = https://3306-danisborges-apiquestao0-1oehoeoc6de.ws-us118.gitpod.io

GET {{url}}/opcoes

###
GET {{url}}/opcoes/2

###
POST {{url}}/opcoes
Content-Type: application/json

{
    "descricao" : "A" 
}

###
PUT {{url}}/opcoes/2
Content-Type: application/json

{

}

###
DELETE {{url}}/opcoes/1